services:
  brick-check:
    build: .
    container_name: brick-check-pipeline
    environment:
      # GitHub CLI needs authentication for API calls
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      # Mount output directories to persist results
      - ./list:/app/list
      - ./info:/app/info
      - ./fail:/app/fail
      # Mount DVC cache to persist downloads between runs
      - dvc-cache:/app/.dvc/cache
    working_dir: /app
    # Override default command for different operations
    command: ["uv", "run", "dvc", "repro"]

  # Service for interactive development
  brick-check-dev:
    build: .
    container_name: brick-check-dev
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
      - dvc-cache:/app/.dvc/cache
    working_dir: /app
    command: ["bash"]
    stdin_open: true
    tty: true

volumes:
  dvc-cache: 