# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  list:
    cmd: source stages/01_list.sh
    deps:
      - stages/01_list.sh
    outs:
      - list/bricks.txt
  install:
    cmd: source stages/02_install.sh
    deps:
      - stages/02_install.sh
      - list/bricks.txt
    outs:
      - info
  verify:
    cmd: uv run stages/03_verify.py
    deps:
      - stages/03_verify.py
      - list/bricks.txt
      - info
    outs:
      - fail/failures.txt:
          cache: false