[project]
name = "brick-check"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "biobricks>=0.3.9",
    "duckdb>=1.3.2",
    "dvc>=3.62.0",
    "pyarrow>=21.0.0",
    "pyspark>=4.0.0",
    "rdflib>=7.1.4",
]
