[project]
name = "brick-check"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "dvc>=3.62.0",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "rdflib>=7.1.4",
]
